#pragma once

// Icons (see assets/icon, generated by tools/make-icons.ps1).
#define IDI_APP            1  // app/window icon (full color teacup)
#define IDI_TRAY_FOR_LIGHT 2  // dark glyph, for a LIGHT taskbar
#define IDI_TRAY_FOR_DARK  3  // light/white glyph, for a DARK taskbar
